## Final Review: Convolution Neural Network

In [ ]:
import numpy as np

x = np.random.randint(0, 10, size=(6, 6))
x

array([[7, 7, 2, 3, 1, 0],
       [1, 6, 7, 8, 2, 9],
       [7, 0, 8, 4, 8, 8],
       [0, 1, 3, 3, 9, 3],
       [0, 8, 9, 5, 3, 2],
       [5, 9, 2, 6, 4, 2]])

In [ ]:
f3 = np.random.randint(-3, 3, size=(3, 3))
f3

array([[-2, -3,  1],
       [ 0,  0,  0],
       [ 1,  2, -1]])

In [ ]:
f5 = np.random.randint(-3, 3, size=(5, 5))
f5

array([[-1,  2,  1, -2, -2],
       [-3, -1,  2,  1, -1],
       [-1, -2,  0, -2, -2],
       [-2, -3, -3,  0, -2],
       [-3, -3,  2,  1,  1]])

Calculate via code the convolutional output of the above array and the filters `f3` and `f5` assuming:
 - `padding="valid"`
 - `padding="same"` (see if `np.pad()` helps)

Also, calculate the output of a `Conv2d` layer using the above input data.

## Pooling

In [ ]:
x = np.random.randint(-10, 10, size=(6, 6))
x

array([[  1,  -8,  -7,   5,  -6,  -7],
       [-10,  -3,   8,   8,  -4,   4],
       [  4,   2,  -3,   6, -10,   9],
       [ -7,   5,   5,  -4,   6,  -1],
       [ -6,   7,  -9,   2,  -4,  -1],
       [  9,   7,  -3,  -1,  -6,  -2]])

Calculate the output of a pooling operation assuming no padding and using a pooling layer:
 - `pool_size = (2, 2)` and `strides=2` and *Max Pooling* is used
 - `pool_size = (3, 3)` and `strides=2` and *Max Pooling* is used
 - `pool_size = (2, 2)` and `strides=1` and *Max Pooling* is used
 - `pool_size = (3, 3)` and `strides=1` and *Max Pooling* is used
 - `pool_size = (2, 2)` and `strides=2` and *Average Pooling* is used
 - `pool_size = (3, 3)` and `strides=2` and *Average Pooling* is used
 - `pool_size = (2, 2)` and `strides=1` and *Average Pooling* is used
 - `pool_size = (3, 3)` and `strides=1` and *Average Pooling* is used


## Parameter calculation

How many trainable parameters does the following model have:

- input data has dimensions (180, 180, 3)
- Conv2D(32, kernel_size=(5, 5), activation="relu")
- AveragePooling(pool_size=(2, 2), strides=2)
- Conv2D(32, kernel_size=(5, 5), activation="relu")
- AveragePooling(pool_size=(2, 2), strides=2)
- Flatten()
- Dense(128, activation="relu")
- Dense(3, activation="softmax")

What 2 properties do convolutional neural networks have that make them much more useful for images than fully-connected networks?

Explain/use **padding**.

Explain/use **strides**.

What is the purpose of a **pooling** layer?

What is the difference between a **parameter** and a **hyperparameter**?

What are training, validation, and test datasets used for?

What is a baseline and how is it used?

What are some ways to deal with overfitting?

What are some common problems when training a model and how can they be overcome?

Data augmentation
 - what is it? why do we do it?
 - how to create a data augmentation layer
