## Pooling

In the code below, we create a single input array (which could be considered a single greyscale image) and pass that through a *max pooling* layer.

In [1]:
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling2D
import numpy as np

In [2]:
x = np.array([[1, 2, 3, 4],       # create a single 2-dimensional image
              [5, 6, 7, 8],
              [9, 1, 11, 12],
              [13, 14, 15, 16]])
print(x)

x = x.reshape([1, 4, 4, 1])  # reshape to (batch_size, h, w, n_c) since the max pooling layer expects arrays with these dimensions

max_pool_2d = MaxPooling2D(pool_size=(2, 2),  # define the max pooling layer
                           strides=2)

max_pool_2d(x).numpy() # pass the input image through the max pooling layer to get our output (.numpy converts from tensor to an array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9  1 11 12]
 [13 14 15 16]]


array([[[[ 6],
         [ 8]],

        [[14],
         [16]]]])

Note that if you change the dimensions of `x` you will need to change the code `x = x.reshape()` to the corresponding values or else you will get an error.

 - Change the values in `x`, calculate by hand what the output should be and then verify by running the code.
 - Change the `strides` to 1, calculate by hand what the output should be and then verify by running the code.
 - Change the `pool_size` to `(3, 3)` and run the code. Are the output dimensions what you would expect? What is happening?
 - Explore some of the other 2D pooling layers found in the [Keras documentation](https://keras.io/api/layers/pooling_layers/)

## Exploring Dimensions

Assuming the input images have a dimesion of 32x32x3 and that there are 6 classes, create the following convolutional network structures and view `.summary()` for each:

- (convolution / pooling) x n +  (1 fully-connected layer) + (output layer)
    - keep increasing `n` until the output shape just before the `Flatten` layer is `(_, <10, <10, _)`
- (convolution / convolution / pooling) x n + (1 fully-connected layer) + (output layer)
    - keep increasing `n` until the output shape just before the `Flatten` layer is `(_, <10, <10, _)`

For all networks, the number of filters should increase as you go deeper into the network (number of filters usually equal $2^m$) and the height and width should decrease.

Use the `name` argument to name each layer but organized into blocks, where (convolution / pooling) would be a single block and (convolution / convolution / pooling) would be a single block.

Fill in the table below using the information in the `.summary()` output for each network created above:

|Convolutional layers | Pooling layers | Trainable parameters | Output shape before `Flatten` |
|:-:|:-:|:-:|:-:|

## Pre-Trained Models

From [Keras Applications](https://keras.io/api/applications/):
 - import the **VGG16** network
 - view its structure
 - compare the depth and number of parameters to your networks from above
 - what data has this network been trained on? How many images are in this dataset? How many classes?

In [5]:
from tensorflow.keras.applications import VGG16

conv_base = VGG16(include_top=False,
                  weights="imagenet", #using the weights of the imagenet dataset
                  input_shape=(244, 244, 3)) #using the infos of the imagenet dataset

In [6]:
conv_base.summary()

Model: "vgg16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 244, 244, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 244, 244, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 244, 244, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 122, 122, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 122, 122, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 122, 122, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 61, 61, 128)       0     

## Keras's functional API

To use these pre-trained networks, we will need to use the *functional* instead of the *sequential* API for building networks in Keras. Even if you don't use a pre-trained network, the functional API is more flexible so it is good to understand the basics of how it works.

### Fully-Connected Model

Using the [Keras documentation](https://keras.io/guides/functional_api/), create and train a fully-connected model for the MNIST data.

### Convolutional Models

Now use the functional API to create and train a convolutional model for the MNIST data. Follow one of the patterns from the **Exploring Dimensions** section above.

Now create a small convolutional neural network for the **Fashion MNIST** data (comes with Keras).

### Convolutional Model with Scaling

Now add a [rescaling](https://keras.io/api/layers/preprocessing_layers/image_preprocessing/rescaling/) layer to the model you created above for the fashion MNIST data.

### Convolutional Model with Scaling and Data Augmentation

Now add data augmentation to the model you created above for the fashion MNIST data. This model will have both scaling and data augmentation.

In [10]:
from tensorflow import keras
from tensorflow.keras import layers
data_augmentation = keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.05),
    layers.RandomZoom(0.2),
    layers.RandomTranslation(
        height_factor=0.1,
        width_factor=0.2,
        fill_mode="nearest")])

In [11]:
data_augmentation