# Practice Lab 3: Random Forest from scratch (we really hope!)

## Data Creation 

In [1]:
from numpy.random import default_rng
import numpy as np

In [5]:
rng = default_rng(45)
new_list = rng.integers(1, 100, (10,6))

In [6]:
new_list

array([[92, 57, 73, 53, 53, 76],
       [70, 81, 56, 51, 42, 78],
       [57, 79, 77, 59, 28, 41],
       [54, 67, 51, 63, 82, 84],
       [12, 72, 93, 53, 57, 96],
       [49, 47, 42, 81, 77, 86],
       [36, 63, 84,  5, 43,  6],
       [30, 12, 42, 70, 41,  5],
       [34, 70, 81, 42, 92, 37],
       [ 7, 16, 55, 11, 18, 13]], dtype=int64)

## Create Bootstrap Samples (Physical)

In [8]:
rng = default_rng(45)
new_list = rng.integers(1, 100, (10,6))

array([[54, 67, 51, 63, 82, 84],
       [30, 12, 42, 70, 41,  5],
       [34, 70, 81, 42, 92, 37],
       [70, 81, 56, 51, 42, 78],
       [70, 81, 56, 51, 42, 78],
       [30, 12, 42, 70, 41,  5],
       [57, 79, 77, 59, 28, 41],
       [30, 12, 42, 70, 41,  5],
       [12, 72, 93, 53, 57, 96],
       [49, 47, 42, 81, 77, 86]], dtype=int64)

## Create Bootstrap Samples (Code)

In [ ]:
# randomly generate 100 datasets from same data
# calculate oob scores for each dataset
# save it in array
# take average of it

In [51]:
boot = []
for i in range(100):
    bs =(rng.choice(new_list, new_list.shape[0], replace=True))
    bs_uniq = np.unique(bs, axis = 0)
    n_unique_row = bs_uniq.shape[0]
    oob_smp = (new_list.shape[0] -  n_unique_row) / new_list.shape[0] 
    boot.append(oob_smp)
boot   

[0.3,
 0.4,
 0.4,
 0.3,
 0.5,
 0.3,
 0.2,
 0.3,
 0.4,
 0.3,
 0.4,
 0.2,
 0.3,
 0.3,
 0.4,
 0.3,
 0.2,
 0.4,
 0.4,
 0.3,
 0.4,
 0.2,
 0.4,
 0.3,
 0.4,
 0.4,
 0.2,
 0.2,
 0.3,
 0.4,
 0.4,
 0.3,
 0.3,
 0.4,
 0.4,
 0.2,
 0.4,
 0.3,
 0.4,
 0.3,
 0.3,
 0.4,
 0.3,
 0.4,
 0.3,
 0.4,
 0.2,
 0.3,
 0.6,
 0.4,
 0.3,
 0.3,
 0.4,
 0.3,
 0.4,
 0.3,
 0.3,
 0.3,
 0.2,
 0.2,
 0.6,
 0.3,
 0.4,
 0.3,
 0.5,
 0.2,
 0.3,
 0.2,
 0.5,
 0.4,
 0.3,
 0.4,
 0.2,
 0.4,
 0.5,
 0.3,
 0.4,
 0.3,
 0.4,
 0.5,
 0.3,
 0.3,
 0.3,
 0.4,
 0.3,
 0.3,
 0.4,
 0.2,
 0.3,
 0.1,
 0.4,
 0.3,
 0.3,
 0.4,
 0.4,
 0.3,
 0.4,
 0.3,
 0.3,
 0.4]

## Average Number of Out-of-Bag Samples

In [62]:
boot = []
for i in range(100):
    bs =(rng.choice(new_list, new_list.shape[0], replace=True))
    bs_uniq = np.unique(bs, axis = 0)
    n_unique_row = bs_uniq.shape[0]
    oob_smp = (new_list.shape[0] -  n_unique_row) / new_list.shape[0] 
    boot.append(oob_smp)
boot   

TypeError: list.append() takes exactly one argument (0 given)

In [52]:
avg_num = np.mean(boot)
avg_num

0.33599999999999997

## Create a Function to Produce a Bootstrap Sample and Corresponding OOB Samples

In [46]:
boot = []
for i in range(100):
    bs =(rng.choice(new_list, new_list.shape[0], replace=True))
    bs_uniq = np.unique(bs, axis = 0)
    n_unique_rown = bs_uniq.shape[0]
    oob_smp = (new_list.shape[0] -  n_unique_rown) / new_list.shape[0] 
    boot.append(oob_smp)
print(new_list, boot)

[[92 57 73 53 53 76]
 [70 81 56 51 42 78]
 [57 79 77 59 28 41]
 [54 67 51 63 82 84]
 [12 72 93 53 57 96]
 [49 47 42 81 77 86]
 [36 63 84  5 43  6]
 [30 12 42 70 41  5]
 [34 70 81 42 92 37]
 [ 7 16 55 11 18 13]] [0.5, 0.5, 0.2, 0.3, 0.1, 0.4, 0.5, 0.3, 0.5, 0.3, 0.4, 0.4, 0.3, 0.2, 0.2, 0.3, 0.4, 0.3, 0.4, 0.3, 0.3, 0.5, 0.3, 0.2, 0.2, 0.4, 0.4, 0.2, 0.4, 0.4, 0.2, 0.3, 0.3, 0.3, 0.5, 0.2, 0.3, 0.4, 0.3, 0.3, 0.2, 0.5, 0.5, 0.4, 0.3, 0.5, 0.4, 0.3, 0.4, 0.4, 0.3, 0.2, 0.4, 0.5, 0.4, 0.2, 0.3, 0.5, 0.2, 0.5, 0.4, 0.4, 0.3, 0.3, 0.5, 0.4, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.4, 0.4, 0.4, 0.3, 0.3, 0.5, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.2, 0.3, 0.2, 0.3, 0.2, 0.5, 0.4, 0.3, 0.3, 0.2, 0.3, 0.2, 0.4, 0.3, 0.2, 0.2]


## Create a Function to Produce a Decision Tree from a Data Sample

## Make Predictions using the Decision Tree 

## Select a Random Subset of Features/Columns from a Data Sample

## Put it All Together